import dotenv from "dotenv";
dotenv.config();

import mongoose from "mongoose";
import Medicine from "./models/Medicine.js";

const demoMedicines = [
  // 1. Prescription Medicines (8 items)
  {
    name: "Napa Extend",
    generic: "Paracetamol 665mg",
    category: "Prescription Medicines",
    brand: "Square Pharmaceuticals",
    price: 15,
    originalPrice: 15,
    discount: 0,
    form: "Tablet",
    rating: 4.8,
    reviewsCount: 120,
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=350",
    description: "Extended release paracetamol formulation for long-lasting relief from mild to moderate pain.",
    stock: 250,
    available: true,
  },
  {
    name: "Ace Plus",
    generic: "Paracetamol + Caffeine",
    category: "Prescription Medicines",
    brand: "Square Pharmaceuticals",
    price: 20,
    originalPrice: 20,
    discount: 0,
    form: "Tablet",
    rating: 4.6,
    reviewsCount: 85,
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?q=80&w=350",
    description: "Fast-acting pain relief combining paracetamol with caffeine to enhance efficacy.",
    stock: 300,
    available: true,
  },
  {
    name: "Alatrol",
    generic: "Cetirizine Hydrochloride",
    category: "Prescription Medicines",
    brand: "Square Pharmaceuticals",
    price: 30,
    originalPrice: 30,
    discount: 0,
    form: "Tablet",
    rating: 4.7,
    reviewsCount: 95,
    image: "https://images.unsplash.com/photo-1628771065518-0d82f1938462?q=80&w=350",
    description: "Second-generation antihistamine used to treat seasonal allergies, hay fever, and hives.",
    stock: 180,
    available: true,
  },
  {
    name: "Fenadin 120",
    generic: "Fexofenadine Hydrochloride",
    category: "Prescription Medicines",
    brand: "Renata",
    price: 80,
    originalPrice: 80,
    discount: 0,
    form: "Tablet",
    rating: 4.5,
    reviewsCount: 64,
    image: "https://images.unsplash.com/photo-1550572017-edd951b55104?q=80&w=350",
    description: "Non-drowsy allergy relief tablets for seasonal allergic rhinitis.",
    stock: 150,
    available: true,
  },
  {
    name: "Azmasol HFA Inhaler",
    generic: "Salbutamol 100mcg",
    category: "Prescription Medicines",
    brand: "Beximco",
    price: 250,
    originalPrice: 250,
    discount: 0,
    form: "Device",
    rating: 4.9,
    reviewsCount: 110,
    image: "https://images.unsplash.com/photo-1607619056574-7b8f304b3b8a?q=80&w=350",
    description: "Metered-dose inhaler for the prevention and treatment of bronchospasm.",
    stock: 80,
    available: true,
  },
  {
    name: "Zimax 500",
    generic: "Azithromycin 500mg",
    category: "Prescription Medicines",
    brand: "Square Pharmaceuticals",
    price: 350,
    originalPrice: 350,
    discount: 0,
    form: "Tablet",
    rating: 4.8,
    reviewsCount: 135,
    image: "https://images.unsplash.com/photo-1631549916768-4119b2e55c26?q=80&w=350",
    description: "Macrolide antibiotic used for treating various bacterial infections of the respiratory tract.",
    stock: 120,
    available: true,
  },
  {
    name: "Sergel 20",
    generic: "Esomeprazole Magnesium",
    category: "Prescription Medicines",
    brand: "Healthcare",
    price: 70,
    originalPrice: 70,
    discount: 0,
    form: "Capsule",
    rating: 4.7,
    reviewsCount: 150,
    image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?q=80&w=350",
    description: "Proton pump inhibitor (PPI) designed for acid reflux and gastroesophageal reflux disease (GERD).",
    stock: 400,
    available: true,
  },
  {
    name: "Fixocard 5",
    generic: "Amlodipine 5mg",
    category: "Prescription Medicines",
    brand: "Incepta",
    price: 60,
    originalPrice: 60,
    discount: 0,
    form: "Tablet",
    rating: 4.6,
    reviewsCount: 48,
    image: "https://images.unsplash.com/photo-1550572017-edd951b55104?q=80&w=350",
    description: "Calcium channel blocker used to treat high blood pressure and chest pain (angina).",
    stock: 200,
    available: true,
  },

  // 2. Pain Relief (6 items)
  {
    name: "Napa 500",
    generic: "Paracetamol 500mg",
    category: "Pain Relief",
    brand: "Square Pharmaceuticals",
    price: 10,
    originalPrice: 12,
    discount: 16,
    form: "Tablet",
    rating: 4.8,
    reviewsCount: 500,
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=350",
    description: "Everyday relief for fever, headaches, body aches, and cold symptoms.",
    stock: 900,
    available: true,
  },
  {
    name: "Fast 500",
    generic: "Paracetamol 500mg",
    category: "Pain Relief",
    brand: "Beximco",
    price: 12,
    originalPrice: 12,
    discount: 0,
    form: "Tablet",
    rating: 4.7,
    reviewsCount: 310,
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?q=80&w=350",
    description: "Analgesic and antipyretic formulation for quick relief of mild pains.",
    stock: 800,
    available: true,
  },
  {
    name: "Rolac 10",
    generic: "Ketorolac Tromethamine",
    category: "Pain Relief",
    brand: "Incepta",
    price: 100,
    originalPrice: 100,
    discount: 0,
    form: "Tablet",
    rating: 4.9,
    reviewsCount: 142,
    image: "https://images.unsplash.com/photo-1628771065518-0d82f1938462?q=80&w=350",
    description: "Non-steroidal anti-inflammatory drug (NSAID) for short-term moderate to severe pain management.",
    stock: 140,
    available: true,
  },
  {
    name: "Flexi 50",
    generic: "Aceclofenac 50mg",
    category: "Pain Relief",
    brand: "Healthcare",
    price: 50,
    originalPrice: 50,
    discount: 0,
    form: "Tablet",
    rating: 4.6,
    reviewsCount: 89,
    image: "https://images.unsplash.com/photo-1550572017-edd951b55104?q=80&w=350",
    description: "Used to relieve pain and inflammation in joint disorders such as osteoarthritis and rheumatoid arthritis.",
    stock: 220,
    available: true,
  },
  {
    name: "Voligel Cream",
    generic: "Diclofenac Diethylammonium",
    category: "Pain Relief",
    brand: "Square Pharmaceuticals",
    price: 120,
    originalPrice: 120,
    discount: 0,
    form: "Ointment",
    rating: 4.7,
    reviewsCount: 76,
    image: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?q=80&w=350",
    description: "Topical pain-relief gel targeting localized muscle aches, joint pains, and sports injuries.",
    stock: 130,
    available: true,
  },
  {
    name: "Himalaya Rumalaya Gel",
    generic: "Herbal Pain Relief Ointment",
    category: "Pain Relief",
    brand: "Himalaya",
    price: 180,
    originalPrice: 200,
    discount: 10,
    form: "Ointment",
    rating: 4.5,
    reviewsCount: 55,
    image: "https://images.unsplash.com/photo-1527799851257-47f9791f0de6?q=80&w=350",
    description: "Natural herbal formulation containing mint and wintergreen oils for immediate joint pain relief.",
    stock: 95,
    available: true,
  },

  // 3. Vitamins & Supplements (6 items)
  {
    name: "Bextrum Gold",
    generic: "Multivitamin & Multimineral A-Z",
    category: "Vitamins & Supplements",
    brand: "Beximco",
    price: 300,
    originalPrice: 350,
    discount: 14,
    form: "Tablet",
    rating: 4.9,
    reviewsCount: 220,
    image: "https://images.unsplash.com/photo-1607619056574-7b8f304b3b8a?q=80&w=350",
    description: "Complete daily multivitamin from A to Zinc, supporting vitality, immunity, and overall energy levels.",
    stock: 180,
    available: true,
  },
  {
    name: "Ceevit Chewable",
    generic: "Vitamin C Chewable (Ascorbic Acid)",
    category: "Vitamins & Supplements",
    brand: "Square Pharmaceuticals",
    price: 25,
    originalPrice: 30,
    discount: 16,
    form: "Tablet",
    rating: 4.8,
    reviewsCount: 430,
    image: "https://images.unsplash.com/photo-1631549916768-4119b2e55c26?q=80&w=350",
    description: "Chewable Vitamin C tablets to boost daily immunity and support skin health.",
    stock: 600,
    available: true,
  },
  {
    name: "Calbo D",
    generic: "Calcium 500mg + Vitamin D3",
    category: "Vitamins & Supplements",
    brand: "Square Pharmaceuticals",
    price: 220,
    originalPrice: 220,
    discount: 0,
    form: "Tablet",
    rating: 4.7,
    reviewsCount: 180,
    image: "https://images.unsplash.com/photo-1550572017-edd951b55104?q=80&w=350",
    description: "Essential mineral and vitamin formulation targeting bone strength and calcium absorption.",
    stock: 350,
    available: true,
  },
  {
    name: "Aristovit B Complex",
    generic: "Vitamin B Complex",
    category: "Vitamins & Supplements",
    brand: "Incepta",
    price: 80,
    originalPrice: 80,
    discount: 0,
    form: "Tablet",
    rating: 4.6,
    reviewsCount: 75,
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?q=80&w=350",
    description: "Synergistic blend of B vitamins supporting nerve health, brain function, and metabolism.",
    stock: 240,
    available: true,
  },
  {
    name: "Seven Seas Cod Liver Oil",
    generic: "Cod Liver Oil USP",
    category: "Vitamins & Supplements",
    brand: "GSK",
    price: 450,
    originalPrice: 500,
    discount: 10,
    form: "Capsule",
    rating: 4.8,
    reviewsCount: 115,
    image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?q=80&w=350",
    description: "Pure source of Omega-3 EPA & DHA along with Vitamins A & D, supporting heart and joint health.",
    stock: 90,
    available: true,
  },
  {
    name: "Neuro-B",
    generic: "Vitamin B1+B6+B12",
    category: "Vitamins & Supplements",
    brand: "Square Pharmaceuticals",
    price: 240,
    originalPrice: 240,
    discount: 0,
    form: "Tablet",
    rating: 4.7,
    reviewsCount: 92,
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=350",
    description: "Nerve nourishing vitamins formulated to prevent and treat deficiencies, neuropathy, and nerve pain.",
    stock: 210,
    available: true,
  },

  // 4. Skin Care (6 items)
  {
    name: "Cetaphil Skin Cleanser",
    generic: "Gentle Cleanser",
    category: "Skin Care",
    brand: "Healthcare",
    price: 850,
    originalPrice: 950,
    discount: 10,
    form: "Ointment",
    rating: 4.9,
    reviewsCount: 205,
    image: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?q=80&w=350",
    description: "Clinically proven gentle, soap-free cleanser designed for sensitive or dry skin.",
    stock: 75,
    available: true,
  },
  {
    name: "Pevisone Cream",
    generic: "Econazole + Triamcinolone",
    category: "Skin Care",
    brand: "Renata",
    price: 140,
    originalPrice: 140,
    discount: 0,
    form: "Ointment",
    rating: 4.6,
    reviewsCount: 42,
    image: "https://images.unsplash.com/photo-1556229174-5e42a09e45af?q=80&w=350",
    description: "Topical steroid and antifungal cream targeting skin rashes and fungal infections.",
    stock: 160,
    available: true,
  },
  {
    name: "Betnovate-N",
    generic: "Betamethasone + Neomycin",
    category: "Skin Care",
    brand: "GSK",
    price: 95,
    originalPrice: 95,
    discount: 0,
    form: "Ointment",
    rating: 4.7,
    reviewsCount: 88,
    image: "https://images.unsplash.com/photo-1527799851257-47f9791f0de6?q=80&w=350",
    description: "Ointment containing corticosteroids and antibiotics to combat inflamed, infected eczema and psoriasis.",
    stock: 220,
    available: true,
  },
  {
    name: "Savlon Antiseptic Cream",
    generic: "Cetrimide + Chlorhexidine",
    category: "Skin Care",
    brand: "Savlon",
    price: 65,
    originalPrice: 70,
    discount: 7,
    form: "Ointment",
    rating: 4.8,
    reviewsCount: 312,
    image: "https://images.unsplash.com/photo-1616683693504-3ea7e9ad6fec?q=80&w=350",
    description: "Classic soothing antiseptic cream to protect cuts, burns, scrapes, and bites from infection.",
    stock: 500,
    available: true,
  },
  {
    name: "Himalaya Neem Face Wash",
    generic: "Purifying Neem Wash",
    category: "Skin Care",
    brand: "Himalaya",
    price: 220,
    originalPrice: 240,
    discount: 8,
    form: "Ointment",
    rating: 4.5,
    reviewsCount: 154,
    image: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?q=80&w=350",
    description: "Herbal face wash combining Neem and Turmeric to target pimples and regulate sebum.",
    stock: 190,
    available: true,
  },
  {
    name: "Dettol Sanitizer Gel",
    generic: "Alcohol Hand Sanitizer",
    category: "Skin Care",
    brand: "Dettol",
    price: 110,
    originalPrice: 120,
    discount: 8,
    form: "Syrup",
    rating: 4.7,
    reviewsCount: 198,
    image: "https://images.unsplash.com/photo-1583947215259-38e31be8751f?q=80&w=350",
    description: "Rinse-free antiseptic hand sanitizer gel killing 99.9% of bacteria and viruses.",
    stock: 450,
    available: true,
  },

  // 5. Hair Care (5 items)
  {
    name: "Selsun Blue Shampoo",
    generic: "Selenium Sulfide 1%",
    category: "Hair Care",
    brand: "GSK",
    price: 650,
    originalPrice: 700,
    discount: 7,
    form: "Syrup",
    rating: 4.8,
    reviewsCount: 112,
    image: "https://images.unsplash.com/photo-1527799851257-47f9791f0de6?q=80&w=350",
    description: "Medicated anti-dandruff shampoo formulated with conditioning agents to target dandruff at the source.",
    stock: 80,
    available: true,
  },
  {
    name: "Nizoder Shampoo",
    generic: "Ketoconazole 2% Shampoo",
    category: "Hair Care",
    brand: "Square Pharmaceuticals",
    price: 180,
    originalPrice: 180,
    discount: 0,
    form: "Syrup",
    rating: 4.7,
    reviewsCount: 125,
    image: "https://images.unsplash.com/photo-1556229174-5e42a09e45af?q=80&w=350",
    description: "Medicated shampoo indicated for the treatment and prophylaxis of dandruff and seborrheic dermatitis.",
    stock: 140,
    available: true,
  },
  {
    name: "Himalaya Hair Fall Cream",
    generic: "Herbal Hair Cream",
    category: "Hair Care",
    brand: "Himalaya",
    price: 320,
    originalPrice: 350,
    discount: 8,
    form: "Ointment",
    rating: 4.4,
    reviewsCount: 68,
    image: "https://images.unsplash.com/photo-1616683693504-3ea7e9ad6fec?q=80&w=350",
    description: "Nourishing daily hair cream containing Eclipta and Licorice to combat hair fall.",
    stock: 110,
    available: true,
  },
  {
    name: "Loprox Shampoo",
    generic: "Ciclopirox Olamine 1%",
    category: "Hair Care",
    brand: "Incepta",
    price: 250,
    originalPrice: 250,
    discount: 0,
    form: "Syrup",
    rating: 4.6,
    reviewsCount: 49,
    image: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?q=80&w=350",
    description: "Prescription-strength antifungal shampoo targeting scalp issues and itching.",
    stock: 95,
    available: true,
  },
  {
    name: "Keranique Regrowth Solution",
    generic: "Minoxidil 2% Solution",
    category: "Hair Care",
    brand: "Healthcare",
    price: 1200,
    originalPrice: 1400,
    discount: 14,
    form: "Syrup",
    rating: 4.7,
    reviewsCount: 62,
    image: "https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?q=80&w=350",
    description: "Clinically proven topical hair regrowth solution targeting thin or receding hair areas.",
    stock: 50,
    available: true,
  },

  // 6. Personal Care (5 items)
  {
    name: "Dettol Liquid Handwash",
    generic: "Anti-bacterial Wash",
    category: "Personal Care",
    brand: "Dettol",
    price: 135,
    originalPrice: 150,
    discount: 10,
    form: "Syrup",
    rating: 4.9,
    reviewsCount: 380,
    image: "https://images.unsplash.com/photo-1555252333-9f8e92e65df9?q=80&w=350",
    description: "Hygienic liquid handwash that protects hands from germs while keeping skin moisturized.",
    stock: 450,
    available: true,
  },
  {
    name: "Savlon Liquid Antiseptic",
    generic: "Antiseptic Liquid",
    category: "Personal Care",
    brand: "Savlon",
    price: 180,
    originalPrice: 180,
    discount: 0,
    form: "Syrup",
    rating: 4.8,
    reviewsCount: 220,
    image: "https://images.unsplash.com/photo-1583947215259-38e31be8751f?q=80&w=350",
    description: "Concentrated antiseptic disinfectant liquid suitable for first aid, laundry, and personal hygiene.",
    stock: 380,
    available: true,
  },
  {
    name: "Dettol Soap Original",
    generic: "Antiseptic Bathing Soap",
    category: "Personal Care",
    brand: "Dettol",
    price: 75,
    originalPrice: 80,
    discount: 6,
    form: "Tablet",
    rating: 4.6,
    reviewsCount: 290,
    image: "https://images.unsplash.com/photo-1607619056574-7b8f304b3b8a?q=80&w=350",
    description: "Legendary germ protection soap bar for standard daily bathing safety.",
    stock: 600,
    available: true,
  },
  {
    name: "Sensoform Toothpaste",
    generic: "Sensitizing Dental Cream",
    category: "Personal Care",
    brand: "GSK",
    price: 190,
    originalPrice: 200,
    discount: 5,
    form: "Ointment",
    rating: 4.7,
    reviewsCount: 88,
    image: "https://images.unsplash.com/photo-1556229174-5e42a09e45af?q=80&w=350",
    description: "Desensitizing toothpaste designed to combat sensitivity in teeth and gums.",
    stock: 150,
    available: true,
  },
  {
    name: "Himalaya Sparkle Toothpaste",
    generic: "Ayurvedic Dental Care",
    category: "Personal Care",
    brand: "Himalaya",
    price: 125,
    originalPrice: 140,
    discount: 10,
    form: "Ointment",
    rating: 4.5,
    reviewsCount: 92,
    image: "https://images.unsplash.com/photo-1527799851257-47f9791f0de6?q=80&w=350",
    description: "Ayurvedic herbal dental formulation designed to remove plaque and provide fresh breath.",
    stock: 180,
    available: true,
  },

  // 7. Baby Care (5 items)
  {
    name: "Pampers Baby Dry Diapers",
    generic: "Baby Diaper Pack",
    category: "Baby Care",
    brand: "Healthcare",
    price: 1850,
    originalPrice: 2000,
    discount: 7,
    form: "Powder",
    rating: 4.8,
    reviewsCount: 142,
    image: "https://images.unsplash.com/photo-1515488042361-404e9250afef?q=80&w=350",
    description: "Ultra-absorbent baby diapers containing locks for up to 12 hours of overnight dry sleep.",
    stock: 65,
    available: true,
  },
  {
    name: "Himalaya Baby Powder",
    generic: "Herbal Baby Powder",
    category: "Baby Care",
    brand: "Himalaya",
    price: 240,
    originalPrice: 260,
    discount: 7,
    form: "Powder",
    rating: 4.7,
    reviewsCount: 118,
    image: "https://images.unsplash.com/photo-1617897903246-719242758050?q=80&w=350",
    description: "Soothes baby skin and keeps it cool, dry, and fresh with olive oil and almond extract.",
    stock: 120,
    available: true,
  },
  {
    name: "Dettol Baby Wipes",
    generic: "Anti-bacterial Wipes",
    category: "Baby Care",
    brand: "Dettol",
    price: 320,
    originalPrice: 350,
    discount: 8,
    form: "Powder",
    rating: 4.6,
    reviewsCount: 84,
    image: "https://images.unsplash.com/photo-1555252333-9f8e92e65df9?q=80&w=350",
    description: "Gentle antiseptic baby wipes formulated for sensitive skin without harsh alcohol.",
    stock: 200,
    available: true,
  },
  {
    name: "Savlon Baby Soap",
    generic: "Mild Moisturizing Soap",
    category: "Baby Care",
    brand: "Savlon",
    price: 90,
    originalPrice: 95,
    discount: 5,
    form: "Tablet",
    rating: 4.8,
    reviewsCount: 76,
    image: "https://images.unsplash.com/photo-1607619056574-7b8f304b3b8a?q=80&w=350",
    description: "Extra gentle moisturizing soap bar designed specifically for baby's soft and sensitive skin.",
    stock: 180,
    available: true,
  },
  {
    name: "Lactogen 1 Infant Formula",
    generic: "Infant Formula Powder",
    category: "Baby Care",
    brand: "Beximco",
    price: 950,
    originalPrice: 950,
    discount: 0,
    form: "Powder",
    rating: 4.9,
    reviewsCount: 165,
    image: "https://images.unsplash.com/photo-1617897903246-719242758050?q=80&w=350",
    description: "Starter milk formula powder suitable for infants from birth up to 6 months of age.",
    stock: 110,
    available: true,
  },

  // 8. Health Devices (5 items)
  {
    name: "Omron Blood Pressure Monitor",
    generic: "Automatic Arm BP Monitor",
    category: "Health Devices",
    brand: "Omron",
    price: 3450,
    originalPrice: 3950,
    discount: 12,
    form: "Device",
    rating: 4.9,
    reviewsCount: 280,
    image: "https://images.unsplash.com/photo-1603398938378-e54eab446dde?q=80&w=350",
    description: "Fully automatic blood pressure monitor featuring Intellisense technology for accurate readings.",
    stock: 50,
    available: true,
  },
  {
    name: "Omron Nebulizer System",
    generic: "Compressor Nebulizer",
    category: "Health Devices",
    brand: "Omron",
    price: 4200,
    originalPrice: 4800,
    discount: 12,
    form: "Device",
    rating: 4.8,
    reviewsCount: 154,
    image: "https://images.unsplash.com/photo-1579684389782-64d84b5e901a?q=80&w=350",
    description: "Highly efficient compressor nebulizer system designed to treat asthma and COPD in children and adults.",
    stock: 35,
    available: true,
  },
  {
    name: "Accu-Chek Instant Glucometer",
    generic: "Blood Glucose Monitor",
    category: "Health Devices",
    brand: "Healthcare",
    price: 1500,
    originalPrice: 1800,
    discount: 16,
    form: "Device",
    rating: 4.8,
    reviewsCount: 195,
    image: "https://images.unsplash.com/photo-1620188467120-5042ed1eb5da?q=80&w=350",
    description: "Fast-reading blood sugar level tracking monitor with instant Bluetooth sync capability.",
    stock: 75,
    available: true,
  },
  {
    name: "Omron Digital Thermometer",
    generic: "Body Thermometer",
    category: "Health Devices",
    brand: "Omron",
    price: 320,
    originalPrice: 350,
    discount: 8,
    form: "Device",
    rating: 4.6,
    reviewsCount: 132,
    image: "https://images.unsplash.com/photo-1579684389782-64d84b5e901a?q=80&w=350",
    description: "Accurate body temperature sensor with beeping indicator for home and professional use.",
    stock: 150,
    available: true,
  },
  {
    name: "Pulse Oximeter OLED",
    generic: "Fingertip Pulse Oximeter",
    category: "Health Devices",
    brand: "Healthcare",
    price: 850,
    originalPrice: 1000,
    discount: 15,
    form: "Device",
    rating: 4.7,
    reviewsCount: 110,
    image: "https://images.unsplash.com/photo-1603398938378-e54eab446dde?q=80&w=350",
    description: "Fingertip pulse blood oxygen saturation level monitor with responsive color OLED display.",
    stock: 90,
    available: true,
  },

  // 9. Ayurveda & Herbal (4 items)
  {
    name: "Himalaya Cystone Tablets",
    generic: "Ayurvedic Renal Care",
    category: "Ayurveda & Herbal",
    brand: "Himalaya",
    price: 220,
    originalPrice: 240,
    discount: 8,
    form: "Tablet",
    rating: 4.8,
    reviewsCount: 125,
    image: "https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?q=80&w=350",
    description: "Natural herbal tablets designed to support kidney health and treat urinary tract stones.",
    stock: 140,
    available: true,
  },
  {
    name: "Dabur Honitus Cough Syrup",
    generic: "Herbal Cough Syrup",
    category: "Ayurveda & Herbal",
    brand: "Dabur",
    price: 110,
    originalPrice: 120,
    discount: 8,
    form: "Syrup",
    rating: 4.7,
    reviewsCount: 205,
    image: "https://images.unsplash.com/photo-1611070973770-b1a6726b0c6a?q=80&w=350",
    description: "Effective non-drowsy herbal cough syrup containing Honey, Tulsi, and Mulethi.",
    stock: 250,
    available: true,
  },
  {
    name: "Dabur Chyawanprash Paste",
    generic: "Ayurvedic Immunity Booster",
    category: "Ayurveda & Herbal",
    brand: "Dabur",
    price: 380,
    originalPrice: 420,
    discount: 9,
    form: "Powder",
    rating: 4.9,
    reviewsCount: 180,
    image: "https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?q=80&w=350",
    description: "Time-tested ayurvedic immunity booster paste loaded with Amla and herbal extracts.",
    stock: 85,
    available: true,
  },
  {
    name: "Himalaya Liv 52 Tablets",
    generic: "Ayurvedic Liver Support",
    category: "Ayurveda & Herbal",
    brand: "Himalaya",
    price: 190,
    originalPrice: 200,
    discount: 5,
    form: "Tablet",
    rating: 4.8,
    reviewsCount: 165,
    image: "https://images.unsplash.com/photo-1611070973770-b1a6726b0c6a?q=80&w=350",
    description: "Natural herbal dietary supplement to improve appetite, digestion, and protect liver health.",
    stock: 300,
    available: true,
  },
];

const seedDB = async () => {
  try {
    // Connect to database
    await mongoose.connect(process.env.MONGO_URI);
    console.log("Connected to MongoDB database for seeding...");

    // Clear existing medicines
    await Medicine.deleteMany({});
    console.log("Cleared existing medicines from collection.");

    // Seed new medicines
    const created = await Medicine.insertMany(demoMedicines);
    console.log(`Successfully seeded ${created.length} demo medicines!`);

    mongoose.connection.close();
    console.log("Database connection closed.");
    process.exit(0);
  } catch (error) {
    console.error("❌ Seeding failed:", error.message);
    process.exit(1);
  }
};

seedDB();
